-- tests/perf/_render_md.lua
--
-- Reads all JSON files in $PM_RUN_DIR and renders a concise Markdown
-- summary to $PM_MD_OUT. Run from tests/perf/run.sh.

local RUN_DIR = assert(os.getenv("PM_RUN_DIR"), "PM_RUN_DIR not set")
local OUT     = assert(os.getenv("PM_MD_OUT"),  "PM_MD_OUT not set")
local SHA     = os.getenv("PM_SHA") or "unknown"

local function read_json(path)
  local f = io.open(path, "r")
  if not f then return nil end
  local s = f:read("*a"); f:close()
  local ok, obj = pcall(vim.json.decode, s)
  if ok then return obj end
end

local function ls(dir)
  local out = {}
  local p = io.popen("ls -1 " .. dir .. " 2>./tmp/null")
  if not p then return out end
  for line in p:lines() do out[#out + 1] = line end
  p:close()
  return out
end

local lines = {}
local function w(s) lines[#lines + 1] = s end

w(string.format("# Perf suite results — `%s`", SHA))
w("")
w("_Generated by `tests/perf/run.sh`._")
w("")

-- Hotspots
local hot = read_json(RUN_DIR .. "/hotspots.json")
if hot then
  local first = hot.results[1]
  if first then
    w(string.format("**Machine**: %s / %s / nvim %s",
      first.machine.os, first.machine.arch, first.machine.nvim))
    w(string.format("**Iterations**: %d (warmup %d)", first.iterations, first.warmup_iterations))
    w("")
  end

  w("## Headless hotspots — FULL_frame per scenario (ms)")
  w("")
  w("| Scenario | n | p50 | p95 | p99 | max | mean |")
  w("|---|---:|---:|---:|---:|---:|---:|")
  for _, r in ipairs(hot.results) do
    local s = r.stages.FULL_frame
    if s then
      w(string.format("| %s | %d | %.4f | %.4f | %.4f | %.4f | %.4f |",
        r.scenario, s.n, s.p50_ms, s.p95_ms, s.p99_ms, s.max_ms, s.mean_ms))
    end
  end
  w("")

  w("## Headless hotspots — per-stage p50 (ms) by scenario")
  w("")
  local stage_keys = { "particles.update", "fire.update", "fire_wall.update",
                       "merge_lists", "renderer.render", "combo.update", "FULL_frame" }
  local header = "| Scenario |"
  local sep    = "|---|"
  for _, k in ipairs(stage_keys) do header = header .. " " .. k .. " |"; sep = sep .. "---:|" end
  w(header); w(sep)
  for _, r in ipairs(hot.results) do
    local row = "| " .. r.scenario .. " |"
    for _, k in ipairs(stage_keys) do
      local s = r.stages[k]
      row = row .. string.format(" %.4f |", s and s.p50_ms or 0)
    end
    w(row)
  end
  w("")

  if hot.primitives and hot.primitives.stages then
    w("## API primitive cost (μs, N=10000)")
    w("")
    w("| Primitive | p50 | p95 | p99 | max |")
    w("|---|---:|---:|---:|---:|")
    for k, s in pairs(hot.primitives.stages) do
      w(string.format("| `%s` | %.2f | %.2f | %.2f | %.2f |",
        k, s.p50_ms * 1000, s.p95_ms * 1000, s.p99_ms * 1000, s.max_ms * 1000))
    end
    w("")
  end
end

-- Memory
local mem = read_json(RUN_DIR .. "/memory.json")
if mem then
  w("## Memory — allocation rate (KB/s of simulated time)")
  w("")
  w("| Scenario | frames | gross KB/s | retained KB/s | wall ms total |")
  w("|---|---:|---:|---:|---:|")
  for _, r in ipairs(mem.results) do
    local s = r.stages.memory
    w(string.format("| %s | %d | %.2f | %.2f | %.2f |",
      r.scenario, s.frames, s.gross_kb_per_s, s.retained_kb_per_s, s.wall_ms_total))
  end
  w("")
end

-- Latency
local lat = read_json(RUN_DIR .. "/latency.json")
if lat then
  w("## Headless spawn-to-render latency (ms)")
  w("")
  w("| Scenario | n | p50 | p95 | p99 | max |")
  w("|---|---:|---:|---:|---:|---:|")
  for _, r in ipairs(lat.results) do
    local s = r.stages.spawn_to_render
    w(string.format("| %s | %d | %.4f | %.4f | %.4f | %.4f |",
      r.scenario, s.n, s.p50_ms, s.p95_ms, s.p99_ms, s.max_ms))
  end
  w("")
end

-- TUI
local tui_files = {}
for _, name in ipairs(ls(RUN_DIR)) do
  if name:match("%.tui%.json$") then tui_files[#tui_files + 1] = RUN_DIR .. "/" .. name end
end
if #tui_files > 0 then
  w("## TUI bench — FULL_frame_reconstructed (ms) + steady-state CPU")
  w("")
  w("| Scenario | fps | fw | frames | p50 | p95 | p99 | max | cpu mean% | cpu p95% |")
  w("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
  for _, p in ipairs(tui_files) do
    local r = read_json(p)
    if r then
      local f = r.stages.FULL_frame_reconstructed or { n = 0, p50_ms = 0, p95_ms = 0, p99_ms = 0, max_ms = 0 }
      local c = r.cpu_summary or { mean_pct = 0, p95_pct = 0 }
      w(string.format("| %s | %s | %s | %d | %.4f | %.4f | %.4f | %.4f | %.2f | %.2f |",
        r.scenario, tostring(r.config_overrides.fps),
        r.config_overrides.fire_wall_enabled and "Y" or "N",
        f.n, f.p50_ms, f.p95_ms, f.p99_ms, f.max_ms,
        c.mean_pct, c.p95_pct))
    end
  end
  w("")
  w("## TUI bench — per-stage p50 (ms) per scenario")
  w("")
  local stage_keys = { "particles.update", "fire.update", "fire_wall.update",
                       "renderer.render", "combo.update", "FULL_frame_reconstructed" }
  local header = "| Scenario |"
  local sep    = "|---|"
  for _, k in ipairs(stage_keys) do header = header .. " " .. k .. " |"; sep = sep .. "---:|" end
  w(header); w(sep)
  for _, p in ipairs(tui_files) do
    local r = read_json(p)
    if r then
      local row = "| " .. r.scenario .. " |"
      for _, k in ipairs(stage_keys) do
        local s = r.stages[k]
        row = row .. string.format(" %.4f |", s and s.p50_ms or 0)
      end
      w(row)
    end
  end
  w("")
end

w("---")
w("Per-bench JSON in `" .. RUN_DIR .. "`.")

local fo = assert(io.open(OUT, "w"))
fo:write(table.concat(lines, "\n"))
fo:close()
io.stderr:write("[_render_md] wrote " .. OUT .. "\n")
vim.cmd("qa!")
